### ISSUE TITLE
Can't search with only one string

### ISSUE THREAD

**Issue by AlManja** [Pushkr/CraigslistToCsv#3]
While searching for "Honda 2015" will work, entering: "x220" will cause an error.

**Comment by Pushkr** [comment]
Hello @AlManja ,

I'll answer your questions from reddit here -
1. The reason you are not able to get any results for "X220" is because, there are no search results reported in salt lake city are for x220. Scraper should ideally display message on console saying "No Results" as you can see in line #83 in scrapper.py. Since you are also still learning like me, I am attaching screen shot below from pycharm which shows how to execute my code and what ideal output should look like for x220.

test.py is entire piece of code that you can run on your machine and the bottom panel shows the output of run.

Please make sure, your test.py/runner.py is in same directory as Scrapper.py otherwise first import statement will fail. 

<img width="896" alt="screen shot 2016-08-24 at 8 00 12 pm" src="https://cloud.githubusercontent.com/assets/14101613/17952095/76d0f68a-6a35-11e6-90ce-346c18e3051f.png">
1. for your 2nd question regarding 'Honda 2015' returning diff year results , unfortunately my script is just a scraper and not a search engine for craiglist. It only pulls data from craiglist what craiglist server decide to return. I am afraid, I cant fix anything related to it. 
2. Regarding g_data, its just a object of `GetCraiglistData` class. You can name it anything you want in your runner program. Like I used `results` in above test.py
3. You dont need to change url by manually changing code using -
    `url = "https://saltlakecity.craigslist.org/"`

the sole reason of creating `GetCraiglistSites` class was to avoid such manual interventions. In test.py above, I showed one method to search in salt lake city using line -

   `results.seturl(site.forcity("salt lake city"))`

another simple way is -

   `result.seturl("https://saltlakecity.craigslist.org/")`

The fix I made yesterday should not cause program to crash  since only a simple 'encoding = UTF-8' option was passed while opening a file.

I hope I answered all of your questions, if you still need clarification, please dont hesitate to reach out. 

Also,If possible, can you please show me what errors you are getting and the code you are using.

**Comment by AlManja** [comment]
Ah I didn't know I can answer here. I will download your code again and try again. I do have all the files in the same folder, I'm using PyCharm. I didn't search for Salt Lake City, I used your default program. Honda 2015 worked for New York City but this time with way more results than before if I remember correctly. If I enter x220 for New York City, default settings, nothing changed, I got msg that around 17 (maybe 19, can't recall) items were found and then program crashed with 3 errors. I saved them see them bellow. I will now download your code again, since I was changing it, to make sure I'm using it completely unchanged. And I will try to recreate the crash by entering x220 at prompt. If I will successfully recreate the problem, then let me know what kind of data you need (my system, libraries versions? etc to give you enough useful information) 

Traceback (most recent call last):
  File "/home/al/PycharmProjects/z_Scraping_Craiglist/Runner.py", line 58, in <module>
    s1.printresults(100)
  File "/home/al/PycharmProjects/z_Scraping_Craiglist/Scrapper.py", line 81, in printresults
    self.**retrievedata**()
  File "/home/al/PycharmProjects/z_Scraping_Craiglist/Scrapper.py", line 157, in **retrievedata**
    title = (id_url.find("span", {"id": "titletextonly"})).text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by AlManja** [comment]
And thank you for all the explanation and help.

**Comment by Pushkr** [comment]
Thank you for traceback. I think I have seen this error before. I'll fix it and let you know when its done.

**Comment by AlManja** [comment]
Hi @Pushkr 

I hope I have some useful information for you. I downloaded your program again, and started fresh :-) I run your program in PyCharm. I started the program by running Runner.py and I got prompt to enter search string. Program is as downloaded, no changes! At prompt I typed:

honda 2015 - works, got 399 results
honda 2016 - still works, got 369 results  
elantra 2016 - not working,  says: "Found 48 items" and few seconds later program crashes. See bellow: (I drag&drop screenshot bellow hope it comes up properly. If not error code is bellow the picture. (all these three search are with default, unchanged code)

![elantra 2016](https://cloud.githubusercontent.com/assets/21198641/17973995/a5588678-6aa1-11e6-89a8-bfd5abfc8693.png)

/usr/bin/python3.5 /home/al/PycharmProjects/z_Scraping_Craiglist/Runner.py
Enter search item : elantra 2016

Found 48 items

Fetching data...
Traceback (most recent call last):
  File "/home/al/PycharmProjects/z_Scraping_Craiglist/Runner.py", line 58, in <module>
    s1.printresults(100)
  File "/home/al/PycharmProjects/z_Scraping_Craiglist/Scrapper.py", line 81, in printresults
    self.**retrievedata**()
  File "/home/al/PycharmProjects/z_Scraping_Craiglist/Scrapper.py", line 157, in **retrievedata**
    title = (id_url.find("span", {"id": "titletextonly"})).text
AttributeError: 'NoneType' object has no attribute 'text'

Process finished with exit code 1

---

I also tried as you explained in your post. I created new py file: test.py, of course in the same folder, and I entered the code exactly as you show me:

![test-py](https://cloud.githubusercontent.com/assets/21198641/17974891/12ea06aa-6aa5-11e6-9182-037003b24a59.png)

from Scrapper import GetCraiglistSites,GetCraiglistData

site = GetCraiglistSites()
results = GetCraiglistData("honda 2015")
results.seturl((site.forcity("salt lake city")))
results.printresults()

Then I run it by running test.py 
Program reports that 19 items were found but after few seconds it crashes:

/usr/bin/python3.5 /home/al/PycharmProjects/z_Scraping_Craiglist/test.py

Found 19 items

Fetching data...
Traceback (most recent call last):
  File "/home/al/PycharmProjects/z_Scraping_Craiglist/test.py", line 6, in <module>
    results.printresults()
  File "/home/al/PycharmProjects/z_Scraping_Craiglist/Scrapper.py", line 81, in printresults
    self.**retrievedata**()
  File "/home/al/PycharmProjects/z_Scraping_Craiglist/Scrapper.py", line 157, in **retrievedata**
    title = (id_url.find("span", {"id": "titletextonly"})).text
AttributeError: 'NoneType' object has no attribute 'text'

Process finished with exit code 1

Lastly I tried to run program directly from the terminal, without using PyCharm. I used again the same search as in try # 3, "elantra 2016" for New Your City, default code, I didn't change anything. Error was the same as inside PyCharm. First I get msg that 48 items were found, then few seconds later program crashes:

[al@ibuypower CraigslistToCsv-master]$ python Runner.py
Enter search item : elantra 2016

Found 48 items

Fetching data...
Traceback (most recent call last):
  File "Runner.py", line 58, in <module>
    s1.printresults(100)
  File "/home/al/Py_projects_other/CraigslistToCsv-master/CraigslistToCsv-master/Scrapper.py", line 81, in printresults
    self.**retrievedata**()
  File "/home/al/Py_projects_other/CraigslistToCsv-master/CraigslistToCsv-master/Scrapper.py", line 157, in **retrievedata**
    title = (id_url.find("span", {"id": "titletextonly"})).text
AttributeError: 'NoneType' object has no attribute 'text'

That way I eliminated possible PyCharm IDE problem. But there shouldn't be any, PyCharm is latest and works otherwise.

Some info in case you need it:
I'm using Linux (Manjaro), kernel is latest 4.7
PyCharm is 2016.2 (latest)
Python3 (3.5.2) 
I don't know how to check library versions for time and Scrapper 
I hope some of this will help you.

**Comment by AlManja** [comment]
Ups, I didn't see your answer I was keep testing :-)

**Comment by Pushkr** [comment]
@AlManja I fixed the issue with AttributeError. Please download the updated code placed in separate 'Issues' branch @ [This link](https://github.com/Pushkr/CraigslistToCsv/blob/Issues/Scrapper.py)

I tried all of above tests you ran and they seems to be working for me. Have it a go and let me know! 

If it works for you, I'll finalize the code.

**Comment by AlManja** [comment]
Hi @Pushkr
I hope I understood you correctly (new at this github) in link you provided there is only new scrapper.py code. So I got from your link only Scrapper.py code but Runner.py is the same, from before, is that correct?

Looks like there is still some problem. First I ran Honda 2015 got 418 found items and everything was OK.

Then I ran elantra 2016 (of course all default code, nothing changed) and as you can see from screen shot, there were 48 found items, just like in the morning with previous version. Then fetching starts and returns over 100 links even that there should be only 48 of them. I'm guessing because over 100 results trace back happens with 'index out of range'? See screenshots bellow. 

(edit:) I did few more local searches, see few more posts bellow and with exception of that one trace back, everything works great. Is there something simple I can troubleshoot on my end, why that trace back happened? But it has to be simple I'm really new to Python. 

![elantra2016_2](https://cloud.githubusercontent.com/assets/21198641/17993043/c127caae-6b09-11e6-8575-e08153e57796.png)
![elantra2016_3_trace_back](https://cloud.githubusercontent.com/assets/21198641/17993046/c4bf9e08-6b09-11e6-9926-586480eddd8c.png)

**Comment by AlManja** [comment]
@Pushkr

SLC now works better :-)
I ran search for Honda 2016 for Salt Lake City as you show me, by running test.py and it found 19 items but also retrieved more (44) items:
![honda_slc](https://cloud.githubusercontent.com/assets/21198641/17993153/a3925210-6b0a-11e6-9375-99fb9613f0c4.png)

Search for x220 for SLC using test.py works as expected (No Results)

**Comment by AlManja** [comment]
@Pushkr

You know, program really works good now. There was only one trace back. And maybe I know why there are those two values different, found items and retrieved items. I searched Honda 2016 for Wyoming (using test.py) and there were 19 found items and 100 retrieved items but glancing over the links, looks like 19 of them (found items) are from Wyoming and the rest of them are form nearby area, Colorado, Idaho... just like you get the same way expanded area on Craig List, so looks like code works pretty good. :-)

![wy-honda-2015](https://cloud.githubusercontent.com/assets/21198641/17993518/a2479502-6b0d-11e6-8094-f98f000bd066.png)
