### ISSUE TITLE
Price always returns "Not Listed" in results

### ISSUE THREAD

**Issue by scottpilkinton** [Pushkr/CraigslistToCsv#6]
Code:

from Scraper import GetCraiglistSites, GetCraiglistData

site = GetCraiglistSites()
g_data = GetCraiglistData("F100")
g_data.seturl(site.forcity("nashville"))
g_data.saveresults()

Here is a sample block of html that contains the price - this is a single post from the search results:

```
<h2 class="postingtitle">
    <span class="icon icon-star" role="button">
        <span class="screen-reader-text">favorite this post</span>
    </span>
    <span class="postingtitletext">
<span id="titletextonly">1954 F100 Project Truck</span> - <span class="price">$4000</span><small> (Lynchburg)</small>        <span class="js-only banish-unbanish">
  <span class="banish" role="button">
    <span class="icon icon-trash" aria-hidden="true"></span>
    <span class="screen-reader-text">hide this posting</span>
  </span>
  <span class="unbanish" role="button">
    <span class="icon icon-trash red" aria-hidden="true"></span>
    unhide
  </span>
</span>
    </span>
</h2>
```

**Comment by Pushkr** [comment]
@scottpilkinton Thank you for pointing out issue. I pushed update to fix it.

**Comment by scottpilkinton** [comment]
Thank you!  I'm still learning Python, so I'll study the fix in hopes to understand it better.  Thanks again!

**Comment by Pushkr** [comment]
@scottpilkinton No problem! I am sorry I should I have explained what I did to fix it earlier. But here it is..

Seems like craigslist developers changed the many tags in feed. So all I had to do to fetch correct price was change my code to look for tag "result-price" instead of "price" .
